# Generated by Django 3.0.8 on 2020-08-29 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relpi_miAPP', '0002_auto_20200827_2207'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidos',
            name='cancelado',
            field=models.BooleanField(default=False, verbose_name='cancelado'),
        ),
        migrations.AddField(
            model_name='pedidos',
            name='terminado',
            field=models.BooleanField(default=False, verbose_name='terminado'),
        ),
    ]
